repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: 21.9b0  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
